name: proxyfrpc
description: A new Flutter project.
version: 1.0.0
homepage: https://github.com/iptodays/proxyfrpc

environment:
  sdk: '>=2.19.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  # https://pub.dev/packages/socks5_proxy
  socks5_proxy: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.iptodays.proxyfrpc
        pluginClass: ProxyfrpcPlugin
      ios:
        pluginClass: ProxyfrpcPlugin